# Generated by Django 5.0.6 on 2024-06-19 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apptodo',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
